### ISSUE TITLE
Cannot read properties of undefined (reading 'create') when Using v8.0 and up in React

### ISSUE THREAD

**Issue by jwolfe890** [AddSearch/js-client-library#67]
I get the below error when trying adding import AddSearchClient from 'addsearch-js-client'; to the top of a React file. 

This does not occur in V7. Really not sure the issue here. 

`Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at ./node_modules/addsearch-js-client/src/api.js (http://localhost:3000/static/js/bundle.js:1490:27)
    at options.factory (http://localhost:3000/static/js/bundle.js:56837:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:56267:32)
    at fn (http://localhost:3000/static/js/bundle.js:56496:21)
    at ./node_modules/addsearch-js-client/src/apifetch.js (http://localhost:3000/static/js/bundle.js:1526:22)
    at options.factory (http://localhost:3000/static/js/bundle.js:56837:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:56267:32)
    at fn (http://localhost:3000/static/js/bundle.js:56496:21)
    at ./node_modules/addsearch-js-client/src/index.js (http://localhost:3000/static/js/bundle.js:1764:23)
    at options.factory (http://localhost:3000/static/js/bundle.js:56837:31)`

**Comment by haoAddsearch** [comment]
@jwolfe890 In which specific version did this issue occur? Can you try the latest patch 0.8.14 and let us know if it works there?

To understand the issue better, did you get the error after importing AddSearchClient (without calling any method from the library) and then compiling your project?

**Comment by haoAddsearch** [comment]
Closing this issue since it should be resolved in 0.8.14
